# .travis.yml setup
sudo: enabled
os: linux
dist: trusty
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

# set up dependencies
install:
  - wget https://raw.githubusercontent.com/niemasd/FAVITES/master/run_favites_docker.py
  - chmod a+x run_favites_docker.py
  - ls -l
  - ./run_favites_docker.py -h
